# Generated by Django 3.2 on 2022-05-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hook_text',
            new_name='가격',
        ),
    ]
