# Generated by Django 3.2 on 2022-05-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_hook_text_post_가격'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='가격',
            new_name='money',
        ),
    ]
