# Generated by Django 3.2 on 2022-05-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_가격_post_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='money',
            new_name='가격',
        ),
    ]
