# Generated by Django 3.2 on 2022-05-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_category_options_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='배기량',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='변속기',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='색상',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='세금미납',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='압류및저당',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='연료',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='연비',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='연식',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='주행거리',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
