# Generated by Django 3.2 on 2022-05-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220512_0909'),
        ('blog', '0017_remove_post_content'),
    ]

    operations = [
    ]
