# Generated by Django 4.0.4 on 2022-05-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220512_0909'),
        ('blog', '0017_remove_post_content'),
    ]

    operations = [
    ]
