# Generated by Django 3.2 on 2022-05-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_merge_20220512_0917'),
        ('blog', '0018_merge_20220512_0922'),
    ]

    operations = [
    ]
