# Generated by Django 3.2 on 2022-05-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20220517_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='분류',
            new_name='category',
        ),
    ]
