# Generated by Django 3.2 on 2022-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_분류_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='연식',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
