# Generated by Django 3.2 on 2022-05-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20220517_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='연식',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
