# Generated by Django 3.2 on 2022-05-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_post_카'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='변속기',
        ),
        migrations.RemoveField(
            model_name='post',
            name='세금미납',
        ),
        migrations.RemoveField(
            model_name='post',
            name='카',
        ),
        migrations.AddField(
            model_name='post',
            name='구동방식',
            field=models.CharField(blank=True, choices=[('경유 ', '경유 '), ('LPG', 'LPG'), ('경유+전기', '경유+전기'), ('하이브리드', '하이브리드'), ('휘발유', '휘발유')], max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='사고유무',
            field=models.CharField(blank=True, choices=[('없음', '없음'), ('있음', '있음')], max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='생산지',
            field=models.CharField(blank=True, choices=[('국산', '국산'), ('해외', '해외')], max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='전속이력',
            field=models.CharField(blank=True, choices=[('없음', '없음'), ('있음', '있음')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='압류및저당',
            field=models.CharField(blank=True, choices=[('없음', '없음'), ('있음', '있음')], max_length=30),
        ),
    ]
