# Generated by Django 3.2 on 2022-05-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20220517_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='구동방식',
            field=models.CharField(blank=True, choices=[('4륜 ', '4륜 '), ('전륜', '전륜'), ('후륜', '후륜')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='연료',
            field=models.CharField(blank=True, choices=[('경유 ', '경유 '), ('LPG', 'LPG'), ('경유+전기', '경유+전기'), ('하이브리드', '하이브리드'), ('휘발유', '휘발유')], max_length=30),
        ),
    ]
