# Generated by Django 3.2 on 2022-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20220518_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='브랜드',
            field=models.CharField(blank=True, choices=[('위에있는분류를 먼저 선택해주세요', '위에있는분류를 먼저 선택해주세요'), ('위에있는분류를 먼저 선택해주세요', '위에있는분류를 먼저 선택해주세요')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='세부차종',
            field=models.CharField(blank=True, choices=[('위에있는분류를 먼저 선택해주세요', '위에있는분류를 먼저 선택해주세요'), ('위에있는분류를 먼저 선택해주세요', '위에있는분류를 먼저 선택해주세요')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='차종',
            field=models.CharField(blank=True, choices=[('위에있는분류를 먼저 선택해주세요', '위에있는분류를 먼저 선택해주세요'), ('위에있는분류를 먼저 선택해주세요', '위에있는분류를 먼저 선택해주세요')], max_length=50, null=True),
        ),
    ]
