# Generated by Django 3.2 on 2022-05-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20220518_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='세차',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
