# Generated by Django 3.2 on 2022-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220517_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='내용',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
