# Generated by Django 3.2 on 2022-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_내용'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='분류',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='head_image',
            new_name='차사진',
        ),
        migrations.AlterField(
            model_name='post',
            name='내용',
            field=models.TextField(blank=True),
        ),
    ]
