# Generated by Django 3.2 on 2022-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20220517_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='car',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
