# Generated by Django 3.2 on 2022-05-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220517_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='car',
            new_name='카',
        ),
    ]
