# Generated by Django 3.2 on 2022-05-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20220517_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='카',
        ),
    ]
