# Generated by Django 3.2 on 2022-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_post_카'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='카',
            field=models.CharField(blank=True, choices=[('S', '현대'), ('M', '기아')], max_length=5),
        ),
    ]
