# Generated by Django 3.2 on 2022-05-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20220517_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='차종',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
