# Generated by Django 3.2 on 2022-05-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20220518_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='연비',
        ),
    ]
