# Generated by Django 3.2 on 2022-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_post_연비'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='브랜드',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
