# Generated by Django 3.2 on 2022-05-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_alter_post_세부차종'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='세차',
        ),
    ]
