# Generated by Django 4.0.4 on 2022-05-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('first', models.CharField(max_length=30)),
                ('second', models.CharField(max_length=30)),
                ('third', models.CharField(max_length=30)),
                ('fourth', models.CharField(max_length=30)),
                ('fiveth', models.CharField(max_length=30)),
            ],
        ),
    ]
