# Generated by Django 4.0.4 on 2022-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_list',
            name='down1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='down2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='down3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='down4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='down5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='present_down',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='present_sub',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='present_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='sub1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='sub2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='sub3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='sub4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='sub5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='value1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='value2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='value3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='value4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car_list',
            name='value5',
            field=models.IntegerField(null=True),
        ),
    ]
