# Generated by Django 3.2 on 2022-05-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
