# Generated by Django 4.0.4 on 2022-05-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_list_test_delete_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('name_detail', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('boost', models.IntegerField()),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('km', models.IntegerField()),
                ('change', models.CharField(max_length=10)),
                ('fure', models.CharField(max_length=10)),
                ('find', models.CharField(max_length=10)),
                ('still', models.IntegerField()),
                ('wheel', models.CharField(max_length=10)),
                ('acc', models.IntegerField()),
                ('distroy', models.IntegerField()),
                ('made', models.CharField(max_length=10)),
                ('new_price', models.IntegerField()),
                ('down_rate', models.FloatField()),
                ('rate_year', models.IntegerField(null=True)),
                ('rate_2023', models.IntegerField(null=True)),
                ('rate_2024', models.IntegerField(null=True)),
                ('rate_2025', models.IntegerField(null=True)),
                ('rate_2026', models.IntegerField(null=True)),
                ('rate_2027', models.IntegerField(null=True)),
                ('rate_2028', models.IntegerField(null=True)),
                ('rate_2029', models.IntegerField(null=True)),
                ('rate_2030', models.IntegerField(null=True)),
            ],
        ),
    ]
