# Generated by Django 3.2 on 2022-05-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
        ('main', '0003_maker_test'),
    ]

    operations = [
    ]
